#
###################################
# Site wide configuration
####################################
#
title: Nikas
email: mail@nikas.cn
description: nikas的个人博客
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: http://nikas1991.github.io

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Nikas
  avatar: avatar.jpg
  job: "前端开发"
  bio: "行至水穷处，坐看云起时"
  email: mail@nikas.com
  disqus-shortname: #nikas1991
  twitter: #username
  facebook: nikas1991
  google:
    plus: #username
    analytics: UA-37464148-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nikas1991
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
